#!/bin/bash

if [ $(id -u) -ne 0 ]; then
   echo >&2 "Must be run as root"
   exit 1
fi

set -e
set -x

. config.env
# install TX2 flavoured version of apweb including fixes

apt-get install -y libtalloc-dev

sudo -u $NORMAL_USER -H bash <<EOF
set -e
set -x

# auto start apweb
APWEB_HOME=~/start_apweb
rm -rf \$APWEB_HOME
if [ ! -d \$APWEB_HOME ]; then
    mkdir \$APWEB_HOME
fi
cp start_apweb.sh \$APWEB_HOME/
cp autostart_apweb.sh \$APWEB_HOME/

# we need to install a modified version of apweb to support APStreamline
# this repository includes defect fixes and the necessary adoptions for the TX2
pushd ~/GitHub
rm -rf APWeb
git clone -b video_streaming https://github.com/mtbsteve/APWeb.git
pushd APWeb
git submodule update --init --recursive
time (make clean | cat)
time (make | cat)
cp web_server \$APWEB_HOME
popd
popd

EOF


# add line below to bottom of /etc/rc.local to call start script
LINE="/bin/bash -c '~$NORMAL_USER/start_apweb/autostart_apweb.sh'"
perl -pe "s%^exit 0%$LINE\\n\\nexit 0%" -i /etc/rc.local

