#!/bin/bash

set -e
set -x

function fail() {
    echo "Fail: $*"
    exit 1
}

STREAM_TO_IP=$1
if test -z "$STREAM_TO_IP"; then
    fail "Need an IP to stream to"
fi
shift

# Enter the port ID to stream to (5600 is typically used with apsync)
STREAM_TO_PORT=5600

# enter here the video device 
SOURCE_DEVICE=/dev/video1

# gst setup for TX2 Development Board onboard camera
# gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM), \
#  width=(int)1920, height=(int)1080, format=(string)NV12, \
#  framerate=(fraction)30/1' ! omxh264enc ! \
#  'video/x-h264, stream-format=(string)byte-stream' ! \
#  rtph264pay ! \
#  udpsink host=$STREAM_TO_IP port=$STREAM_TO_PORT

# gst setup for ZED stereo camera. We are streaming the left camera view
gst-launch-1.0 v4l2src device=$SOURCE_DEVICE ! video/x-raw, width=3840, height=1080 ! videocrop top=0 left=0 right=1920 bottom=0 ! tee name=t ! queue ! videoconvert ! omxh264enc ! video/x-h264, stream-format=byte-stream ! h264parse ! rtph264pay ! udpsink host=$STREAM_TO_IP port=$STREAM_TO_PORT t. ! queue ! videoconvert

